In [37]:
import pandas as pd
from sklearn.preprocessing import RobustScaler
import category_encoders as ce
from sklearn.preprocessing import LabelEncoder
import joblib

In [38]:
data = pd.read_csv('./data/data.csv')

In [39]:
data.head()

,Area,Year,Food Inflation Rate,Raw GDP,GDP Growth Rate,Item,Item Price Per Tonne,Overall Inflation Rate,Import Rate,Export Rate,Unemployment Rate,Official Exchange Rate,label
0,Albania,2012,2.404087,12319.779604,-4.430218,Apples,369.7,3.2,-6.930669,0.293588,13.376,108.184167,0
1,Albania,2012,2.404087,12319.779604,-4.430218,Apricots,489.9,3.2,-6.930669,0.293588,13.376,108.184167,0
2,Albania,2012,2.404087,12319.779604,-4.430218,Barley,316.1,3.2,-6.930669,0.293588,13.376,108.184167,0
3,Albania,2012,2.404087,12319.779604,-4.430218,"Beans, dry",1562.2,3.2,-6.930669,0.293588,13.376,108.184167,0
4,Albania,2012,2.404087,12319.779604,-4.430218,Cabbages,203.4,3.2,-6.930669,0.293588,13.376,108.184167,0

In [92]:
# binary_encoder = ce.BinaryEncoder(cols=['Item', 'Area'])
# data=binary_encoder.fit_transform(data)

In [40]:
label_encoder = LabelEncoder()

In [41]:
data['Item'] = label_encoder.fit_transform(data['Item'])

C:\Users\Tamara\venv\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Tamara\venv\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [42]:
data['Area'] = label_encoder.fit_transform(data['Area'])

C:\Users\Tamara\venv\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Tamara\venv\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [43]:
joblib.dump(label_encoder, 'label_encoder.joblib')

['label_encoder.joblib']

In [44]:
numerical_columns=['Food Inflation Rate', 'Raw GDP', 'Item Price Per Tonne', 'GDP Growth Rate','Overall Inflation Rate', 'Import Rate', 'Export Rate', 'Unemployment Rate', 'Official Exchange Rate', 'Year']

In [45]:
numerical_columns

['Food Inflation Rate',
 'Raw GDP',
 'Item Price Per Tonne',
 'GDP Growth Rate',
 'Overall Inflation Rate',
 'Import Rate',
 'Export Rate',
 'Unemployment Rate',
 'Official Exchange Rate',
 'Year']

In [46]:
scaler = RobustScaler()

data[numerical_columns] = scaler.fit_transform(data[numerical_columns])

C:\Users\Tamara\venv\lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\Tamara\venv\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Tamara\venv\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Tamara\venv\lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\Tamara\venv\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Tamara\venv\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [47]:
joblib.dump(scaler, 'scaler.joblib')

['scaler.joblib']

In [48]:
data.head()

,Area,Year,Food Inflation Rate,Raw GDP,GDP Growth Rate,Item,Item Price Per Tonne,Overall Inflation Rate,Import Rate,Export Rate,Unemployment Rate,Official Exchange Rate,label
0,0,-0.833333,0.160705,-0.422628,-0.784202,2,-0.299190,0.708333,-1.896689,-0.729945,0.845572,19.024737,0
1,0,-0.833333,0.160705,-0.422628,-0.784202,3,-0.229156,0.708333,-1.896689,-0.729945,0.845572,19.024737,0
2,0,-0.833333,0.160705,-0.422628,-0.784202,9,-0.330420,0.708333,-1.896689,-0.729945,0.845572,19.024737,0
3,0,-0.833333,0.160705,-0.422628,-0.784202,10,0.395618,0.708333,-1.896689,-0.729945,0.845572,19.024737,0
4,0,-0.833333,0.160705,-0.422628,-0.784202,16,-0.396085,0.708333,-1.896689,-0.729945,0.845572,19.024737,0

In [49]:
data.to_csv('./data/data-processed.csv', index=False)