In [1]:
import pandas as pd
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import LabelEncoder
import joblib

In [2]:
data = pd.read_csv('./data/data.csv')

In [3]:
data.head()

,Area,Year,Food Inflation Rate,Raw GDP,GDP Growth Rate,Item,Item Price Per Tonne,Overall Inflation Rate,Import Rate,Export Rate,Unemployment Rate,Official Exchange Rate,label
0,Albania,2012,2.404087,12319.779604,-4.430218,Apples,369.7,3.2,-6.930669,0.293588,13.376,108.184167,0
1,Albania,2012,2.404087,12319.779604,-4.430218,Apricots,489.9,3.2,-6.930669,0.293588,13.376,108.184167,0
2,Albania,2012,2.404087,12319.779604,-4.430218,Barley,316.1,3.2,-6.930669,0.293588,13.376,108.184167,0
3,Albania,2012,2.404087,12319.779604,-4.430218,"Beans, dry",1562.1,3.2,-6.930669,0.293588,13.376,108.184167,0
4,Albania,2012,2.404087,12319.779604,-4.430218,Cabbages,203.4,3.2,-6.930669,0.293588,13.376,108.184167,0

Uncomment this code for encoding with binary encoder

In [4]:
# binary_encoder = ce.BinaryEncoder(cols=['Item', 'Area'])
# data = binary_encoder.fit_transform(data)

Uncomment this code for encoding with label encoder

In [5]:
label_encoder = LabelEncoder()

In [6]:
data['Item'] = label_encoder.fit_transform(data['Item'])

In [7]:
data['Area'] = label_encoder.fit_transform(data['Area'])

In [8]:
joblib.dump(label_encoder, 'label_encoder.joblib')

['label_encoder.joblib']

In [9]:
numerical_columns=['Food Inflation Rate', 'Raw GDP', 'Item Price Per Tonne', 'GDP Growth Rate','Overall Inflation Rate', 'Import Rate', 'Export Rate', 'Unemployment Rate', 'Official Exchange Rate', 'Year', 'Item', 'Area']

In [10]:
numerical_columns

['Food Inflation Rate',
 'Raw GDP',
 'Item Price Per Tonne',
 'GDP Growth Rate',
 'Overall Inflation Rate',
 'Import Rate',
 'Export Rate',
 'Unemployment Rate',
 'Official Exchange Rate',
 'Year',
 'Item',
 'Area']

In [11]:
scaler = RobustScaler()

data[numerical_columns] = scaler.fit_transform(data[numerical_columns])

In [12]:
joblib.dump(scaler, 'scaler.joblib')

['scaler.joblib']

In [13]:
data.head()

,Area,Year,Food Inflation Rate,Raw GDP,GDP Growth Rate,Item,Item Price Per Tonne,Overall Inflation Rate,Import Rate,Export Rate,Unemployment Rate,Official Exchange Rate,label
0,-0.941176,-0.833333,0.059774,-0.422008,-0.726318,-1.000000,-0.304643,0.555556,-1.628717,-0.716019,0.893405,19.022788,0
1,-0.941176,-0.833333,0.059774,-0.422008,-0.726318,-0.986486,-0.236288,0.555556,-1.628717,-0.716019,0.893405,19.022788,0
2,-0.941176,-0.833333,0.059774,-0.422008,-0.726318,-0.918919,-0.335125,0.555556,-1.628717,-0.716019,0.893405,19.022788,0
3,-0.941176,-0.833333,0.059774,-0.422008,-0.726318,-0.905405,0.373454,0.555556,-1.628717,-0.716019,0.893405,19.022788,0
4,-0.941176,-0.833333,0.059774,-0.422008,-0.726318,-0.824324,-0.399215,0.555556,-1.628717,-0.716019,0.893405,19.022788,0

In [14]:
data.to_csv('./data/data-processed.csv', index=False)